// <auto-generated />
namespace WinCompetitionsParsing.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class adk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adk));
        
        string IMigrationMetadata.Id
        {
            get { return "201811080941378_adk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
